### ISSUE TITLE
 [MAC-크롬-전체 게시물 페이지] 현재시간 표시가 다릅니다.

### ISSUE THREAD

**Issue by donet12** [100-hours-a-week/2-aaron-hwang-community-fe#14]
**버그 설명**
게시물을 작성했을때 현제 시간과 다릅니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시물을 작성한다.
2. 게시물 전체 페이지를 본다.

**예상한 동작**
현재 시간이 뜨는걸 예상했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/366b41a0-5b4e-4fd2-90ba-e0118f5051f5)

**데스크톱:**
 - OS: mac
 - Browser: chrome

**Comment by JiwonHwang01** [comment]
리눅스 localtime 변경으로 해결했습니다. 감사합니다.
