### ISSUE TITLE
 [MAC-크롬-회원정보 수정페이지] 회원 프로필 수정 후 헤더 프로필 수정 안됨

### ISSUE THREAD

**Issue by yosep98** [100-hours-a-week/2-aaron-hwang-community-fe#15]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. 회원정보 페이지 닉네임, 프로필 수정
2. 수정 후 게시글 페이지 이동

**예상한 동작**
게시글 헤더 프로필도 수정된 프로필로 변경을 예상

**스크린샷**
![스크린샷 2024-12-18 오후 3 31 05](https://github.com/user-attachments/assets/a6552f1f-2622-4b8d-bf01-4e00f3639367)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [hrome]
 - Version [22]

**Comment by JiwonHwang01** [comment]
회원 정보 수정 이후 세션 업데이트로 해결했습니다. 감사합니다.
