### ISSUE TITLE
 [MAC-Chrome-850-댓글] 댓글 렌더링 문제 

### ISSUE THREAD

**Issue by gelong25** [100-hours-a-week/2-aaron-hwang-community-fe#18]
**버그 설명**
댓글 작성 후 댓글이 성공적으로 작성되었다는 alert 메시지가 표시되고 댓글 수가 증가하지만 작성된 댓글이 목록에 렌더링되지 않는 문제가 발생합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세 보기 페이지로 이동합니다. 
2. 해당 글에 댓글을 작성합니다. 
3. 작성 완료 후 댓글이 렌덜이 되지 않는 것을 확인합니다. 

**예상한 동작**
댓글을 작성하면 작성한 내용이 댓글 목록에 표시 돼야 합니다. 

**스크린샷**
![스크린샷 2024-12-18 14 55 53](https://github.com/user-attachments/assets/769eb39c-1123-49e7-b1c3-3695949ccc30)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by JiwonHwang01** [comment]
회원가입 쪽에 문제가 있어서 연쇄적으로 발생한 문제 같습니다
