### ISSUE TITLE
 [MacOS-Arc-437-회원가입] 회원가입 실패라 뜨지만 내부적으론 성공합니다.

### ISSUE THREAD

**Issue by Unagi-zoso** [100-hours-a-week/2-aaron-hwang-community-fe#9]
**버그 설명**
회원가입 요청 후 실패했단 알람이 뜨지만 로그인 시 성공합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지로 갑니다.
2. 회원가입을 시도합니다.
3. 실패 요청을 받습니다.
4. 로그인을 시도합니다.
5. 성공합니다.

**예상한 동작**
회원가입이 성공하길 기대했습니다.

**스크린샷**
![스크린샷 2024-12-18 오후 2 42 40](https://github.com/user-attachments/assets/e1cc31c7-5f23-4973-a29b-b2bf88d2dcc5)
![스크린샷 2024-12-18 오후 2 42 59](https://github.com/user-attachments/assets/34a864de-34b2-4c88-b51a-b232a6a8240a)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS 14
 - Browser Arc

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by JiwonHwang01** [comment]
User 모델 단에서 image 처리 중 오류가 있었던 것으로 파악했습니다. 덕분에 해결했습니다. 감사합니다ㅎㅎ
